package com.ecommerce.user.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;
import org.springframework.data.mongodb.core.index.Indexed;
import java.time.LocalDateTime;

/**
 * @Document(collection = "users")
 *   → maps this class to the "users" collection in MongoDB
 *   → equivalent to a table in SQL
 *
 * Each field becomes a field in the MongoDB document (JSON):
 * {
 *   "_id":       "64ab...",           ← generated by MongoDB
 *   "name":      "Chirag",
 *   "email":     "chirag@test.com",   ← @Indexed(unique=true) → MongoDB creates an index
 *   "password":  "$2a$10$...",        ← BCrypt hash, never plain text
 *   "createdAt": "2026-04-29T..."
 * }
 */
@Document(collection = "users")
public class User {
    @Id                                    // Maps to MongoDB _id field
    private String id;

    @Field("name")
    private String name;

    @Indexed(unique = true)                // MongoDB unique index on email — fast lookups
    @Field("email")
    private String email;

    @Field("password")                     // Stored as BCrypt hash
    private String password;

    private LocalDateTime createdAt = LocalDateTime.now();

    public User() {}
    public User(String name, String email, String password) {
        this.name = name; this.email = email; this.password = password;
    }

    public String getId() { return id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }
    public LocalDateTime getCreatedAt() { return createdAt; }
}
